import asyncio
import os
from pathlib import Path
from dotenv import load_dotenv

# Force reload of environment variables to get the new token
load_dotenv(override=True)

from core.publisher import Publisher
from utils.logger import setup_logger

logger = setup_logger("retry_publish")

async def retry():
    logger.info("Retrying publication for 'QuickAI Ideas'...")
    
    publisher = Publisher()
    asset_path = Path(r"d:\mybestie\data\assets\quickai_ideas")
    
    metadata = {
        "title": "QuickAI Ideas",
        "description": "AI Tools for Content Creation - Generated by Antigravity",
        "version": "1.0.0",
        "qa_status": "passed", # We manually fixed the syntax error
        "tech_stack": "Python, React"
    }
    
    repo_url, store_link = await publisher.publish(asset_path, metadata)
    logger.info(f"Retry Result: GitHub={repo_url}, Store={store_link}")

if __name__ == "__main__":
    asyncio.run(retry())
