import shutil
import json
from pathlib import Path
from utils.logger import setup_logger

logger = setup_logger("packager")

class Packager:
    def __init__(self):
        pass

    async def package_asset(self, asset_path: Path, metadata: dict):
        """
        Finalizes the asset package.
        """
        logger.info(f"Packaging asset: {asset_path}")
        
        # 1. Create metadata.json
        meta_file = asset_path / "metadata.json"
        with open(meta_file, "w", encoding="utf-8") as f:
            json.dump(metadata, f, indent=4)
        
        # 2. Add LICENSE if missing (MIT Default)
        license_file = asset_path / "LICENSE"
        if not license_file.exists():
            with open(license_file, "w", encoding="utf-8") as f:
                f.write("MIT License\n\nCopyright (c) 2024 Generated by Antigravity\n\nPermission is hereby granted...")

        # 3. Create ZIP archive (Optional, for distribution)
        shutil.make_archive(str(asset_path), 'zip', asset_path)
        logger.info(f"Asset packaged and zipped at {asset_path}.zip")
